# Use the official Node.js LTS (Long Term Support) image
FROM node:18-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json (if available)
COPY package*.json ./

# Install project dependencies
RUN npm install

COPY . .

ENV NODE_ENV=development
ARG PUBLIC_API_URL
ENV PUBLIC_API_URL=${PUBLIC_API_URL}

# Expose the development server port (default is 5173 for Vite)
EXPOSE 5173
