"""0001_add_search_filter_to_messages

Revision ID: 8c9f2cc9c395
Revises: 
Create Date: 2024-12-11 13:41:49.304106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c9f2cc9c395'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('search_filters', sa.JSON(), nullable=True))
    # ### end Alembic commands ###
    op.execute("ALTER TABLE messages MODIFY search_filters JSON AFTER formatted_content;")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'search_filters')
    # ### end Alembic commands ### 