"""0002_add_message_augmentations

Revision ID: 9d8cd23216bd
Revises: 8c9f2cc9c395
Create Date: 2024-12-11 19:48:45.886314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d8cd23216bd'
down_revision: Union[str, None] = '8c9f2cc9c395'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('user_query', sa.Text(), nullable=True))
    
    op.execute("ALTER TABLE messages MODIFY user_query VARCHAR(255) AFTER search_filters;")
    
    op.add_column('messages', sa.Column('rewritten_query_for_vector_base', sa.Text(), nullable=True))
    
    op.execute("ALTER TABLE messages MODIFY rewritten_query_for_vector_base VARCHAR(255) AFTER user_query;")
    
    op.add_column('messages', sa.Column('rewritten_query_for_llm', sa.Text(), nullable=True))
    
    op.execute("ALTER TABLE messages MODIFY rewritten_query_for_llm VARCHAR(255) AFTER rewritten_query_for_vector_base;")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'rewritten_query_for_llm')
    op.drop_column('messages', 'rewritten_query_for_vector_base')
    op.drop_column('messages', 'user_query')
    # ### end Alembic commands ### 