"""0003_add_document_rerank_score

Revision ID: f0f56bbf8ad6
Revises: 9d8cd23216bd
Create Date: 2024-12-12 22:02:49.445285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f0f56bbf8ad6'
down_revision: Union[str, None] = '9d8cd23216bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('rerank_score', sa.Float(), nullable=True))
    
    op.execute("ALTER TABLE documents MODIFY rerank_score FLOAT AFTER score;")
    
    op.alter_column('messages', 'user_query',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('messages', 'rewritten_query_for_vector_base',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('messages', 'rewritten_query_for_llm',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'rewritten_query_for_llm',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               existing_nullable=True)
    op.alter_column('messages', 'rewritten_query_for_vector_base',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               existing_nullable=True)
    op.alter_column('messages', 'user_query',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               existing_nullable=True)
    op.drop_column('documents', 'rerank_score')
    # ### end Alembic commands ### 